baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Home"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Research"
  url = "/pages/research/"
  weight = 2
[[menu.main]]
  name = "Publications"
  url = "/pages/publications/"
  weight = 4
[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 5
[[menu.main]]
  name = "Curriculum-Vitae"
  url = "/pages/cv/"
  weight = 99
[[menu.main]]
  name = "Contact"
  url = "/pages/contact/"
  weight = 100

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = """
  [Twitter](https://twitter.com/johannes_nauta) |
  [Github](https://github.com/github-jnauta) |
  [Keybase](https://keybase.io/jnautahan)

  \n (Theme built with [Hugo](https://gohugo.io/) using \
  the [Hugo-classic](https://themes.gohugo.io/themes/hugo-classic/) made by
  [Kellen Evan Person](https://goodroot.ca/))
"""

